name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q > result.log || true

    - name: Add comment to PR with results
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### Résultats des tests
          $(tail -n 10 result.log)  # Affiche les 10 dernières lignes du log des tests
          
    - name: Add detailed feedback
      run: |
        if grep -q "FAILED" result.log; then
          echo "Certains tests ont échoué. Voici quelques pistes d'amélioration..." >> feedback.txt
        else
          echo "Félicitations ! Tous les tests ont réussi." >> feedback.txt
        fi
